name: 'project_batch_processing'  # Name of your project
version: '1.0'  # Version of your project
profile: 'project_batch_processing'  # The name of your profile in profiles.yml

# Paths to directories and settings
model-paths: ["/home/mauricio/git/project-batch-processing/dbt/models"]  # Location of your DBT models
analysis-paths: [/home/mauricio/git/project-batch-processing/dbt/analysys"]  # Path for analysis files

clean-targets:
  - "target"
  - "dbt_modules"
  

  
