name: 'project_batch_processing'  # Name of your project
version: '1.0' 
profile: 'project_batch_processing'  # The name of your profile in profiles.yml

# Paths to directories and settings
model-paths: ["dbt/models"]
macro-paths: ["dbt/macros"]

models:
  project_batch_processing:
    transformed_data:
      materialized: view 
     
# Clean-targets - directories to clean during the dbt run
clean-targets:
  - "target"
  - "dbt_modules"